package cz.muni.fi.jboss.migration.spi;

import cz.muni.fi.jboss.migration.MigrationContext;
import cz.muni.fi.jboss.migration.ex.ApplyMigrationException;
import cz.muni.fi.jboss.migration.ex.CliScriptException;
import cz.muni.fi.jboss.migration.ex.LoadMigrationException;
import cz.muni.fi.jboss.migration.ex.MigrationException;
import org.w3c.dom.Node;

import java.io.FileNotFoundException;
import java.util.List;

/**
 * Interface for migrators
 *
 * @author Roman Jakubco
 *         Date: 1/24/13
 *         Time: 10:35 AM
 */

public interface IMigrator {

    /**
     * Method for loading all files from AS5 and converting them to objects for migration which are then stored in Mig-
     * rationContext
     *
     * @param ctx context of migration with necessary object and information
     * @throws LoadMigrationException if loading fails for different reasons
     */
    public void loadAS5Data(MigrationContext ctx) throws LoadMigrationException;

    /**
     * Method for inserting migrated data to fresh standalone file.
     *
     * @param ctx context of migration with necessary object and information
     * @throws ApplyMigrationException if something went wrong when working with standalone xml file
     */
    public void apply(MigrationContext ctx) throws ApplyMigrationException;

    /**
     * Method for generating Dom nodes from data stored in MigrationContext. Basically method representing actual migration
     * of the XML configuration files from AS5 to AS7.
     *
     * @param ctx context of migration with necessary object and information
     * @return List of all nodes, which represent migrated configuration of AS5
     * @throws MigrationException if something when wrong
     */
    public List<Node> generateDomElements(MigrationContext ctx) throws MigrationException;

    /**
     * Method for generating CLI scripts from migrated data, which are generated by generateDomElements.
     *
     * @param ctx context of migration with necessary object and information
     * @return List of CLI scripts, which represent migrated configuration of AS5
     * @throws CliScriptException
     */
    public List<String> generateCliScripts(MigrationContext ctx) throws CliScriptException;
}
